// Read-only reference from CSV/API
export interface RequiredItem {
  id: string; // e.g., "rusted-gear"
  name: string; // e.g., "Rusted Gear"
  rarity: Rarity;
}

export type Rarity = "Common" | "Uncommon" | "Rare" | "Epic" | "Legendary";

// User State (Persisted)
export interface AppState {
  keeplists: Keeplist[];
  settings: AppSettings;
}

export interface AppSettings {
  showCompleted: boolean;
  activeKeeplistIds: string[]; // IDs of keeplists to show (empty = all active)
}

export interface Keeplist {
  id: string; // Autogenerated slug from the name
  name: string; // e.g., "Workbenches", "Expedition 2"
  isSystem: boolean; // true = provided by app, false = user made
  items: KeeplistItem[];
}

export interface KeeplistItem {
  itemId: string; // Relates to RequiredItem.id
  qtyOwned: number; // User input
  qtyRequired: number; // Target (from system or user). NOTE: If 0, implies "infinite demand"
  isCompleted: boolean; // Derived state (owned >= required)
}

// API Response types from MetaForge
export interface ApiItem {
  id: string;
  name: string;
  description: string;
  item_type: string;
  icon: string;
  rarity: string;
  value: number;
  workbench: string | null;
  loot_area: string | null;
  sources: string[] | null;
  ammo_type: string | null;
  locations: string[];
  guide_links: string[];
  game_asset_id: number;
  created_at: string;
  updated_at: string;
}

export interface ApiResponse {
  data: ApiItem[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
    hasNextPage: boolean;
    hasPrevPage: boolean;
  };
}

// Helper to get item image placeholder
export const getItemImage = (slug: string): string =>
  `https://cdn.metaforge.app/arc-raiders/icons/${slug}.webp`;

// Rarity color mapping
export const rarityColors: Record<Rarity, string> = {
  Common: "gray",
  Uncommon: "green",
  Rare: "blue",
  Epic: "purple",
  Legendary: "amber",
};
