import { useState, useMemo, useEffect, useRef } from "react";
import {
  Plus,
  Trash2,
  Download,
  Save,
  ChevronDown,
  ChevronRight,
  Search,
} from "lucide-react";
import { systemKeeplists } from "../data/systemKeeplists";
import { allItems, getItemByIdWithFallback } from "../data/allItems";
import { ConfirmDialog } from "./ConfirmDialog";
import { useConfirmDialog } from "../hooks/useConfirmDialog";
import type { Keeplist } from "../types";

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function generateKeeplistsCode(keeplists: Keeplist[]): string {
  const itemsCode = keeplists
    .map((kl) => {
      const itemsStr = kl.items
        .map(
          (item) =>
            `      { itemId: "${item.itemId}", qtyOwned: 0, qtyRequired: ${item.qtyRequired}, isCompleted: false }`
        )
        .join(",\n");

      return `  {
    id: "${kl.id}",
    name: "${kl.name}",
    isSystem: true,
    items: [
${itemsStr},
    ],
  }`;
    })
    .join(",\n");

  return `import type { Keeplist } from "../types";

// System keeplists - default state provided by the app
// Generated by Keeplist Builder on ${new Date().toISOString()}
export const systemKeeplists: Keeplist[] = [
${itemsCode},
];
`;
}

export function KeeplistBuilder() {
  const [keeplists, setKeeplists] = useState<Keeplist[]>(() =>
    JSON.parse(JSON.stringify(systemKeeplists))
  );
  const [expandedLists, setExpandedLists] = useState<Set<string>>(
    new Set(systemKeeplists.map((kl) => kl.id))
  );
  const [itemSearch, setItemSearch] = useState("");
  const [addingToList, setAddingToList] = useState<string | null>(null);
  const [newListName, setNewListName] = useState("");
  const [writeStatus, setWriteStatus] = useState<string | null>(null);
  const [highlightedIndex, setHighlightedIndex] = useState(0);
  const [focusedQtyItem, setFocusedQtyItem] = useState<{
    keeplistId: string;
    itemId: string;
  } | null>(null);
  const [createError, setCreateError] = useState<string | null>(null);
  const listRef = useRef<HTMLDivElement>(null);
  const qtyInputRefs = useRef<Map<string, HTMLInputElement>>(new Map());
  const { confirm, dialogProps } = useConfirmDialog();

  const isDev = import.meta.env.DEV;

  // Filter available items for adding
  const filteredItems = useMemo(() => {
    if (!itemSearch.trim()) return allItems.slice(0, 20);
    const query = itemSearch.toLowerCase();
    return allItems
      .filter((item) => item.name.toLowerCase().includes(query))
      .slice(0, 20);
  }, [itemSearch]);

  // Reset highlighted index when search or filtered items change
  useEffect(() => {
    setHighlightedIndex(0);
  }, [itemSearch]);

  // Get selectable items (not already in the keeplist)
  const getSelectableItems = (keeplistId: string) => {
    const keeplist = keeplists.find((kl) => kl.id === keeplistId);
    if (!keeplist) return filteredItems;
    return filteredItems.filter(
      (item) => !keeplist.items.some((i) => i.itemId === item.id)
    );
  };

  // Handle keyboard navigation in autocomplete
  const handleSearchKeyDown = (e: React.KeyboardEvent, keeplistId: string) => {
    const selectableItems = getSelectableItems(keeplistId);

    switch (e.key) {
      case "ArrowDown":
        e.preventDefault();
        setHighlightedIndex((prev) =>
          prev < selectableItems.length - 1 ? prev + 1 : prev
        );
        break;
      case "ArrowUp":
        e.preventDefault();
        setHighlightedIndex((prev) => (prev > 0 ? prev - 1 : 0));
        break;
      case "Enter":
        e.preventDefault();
        if (selectableItems[highlightedIndex]) {
          addItemToList(keeplistId, selectableItems[highlightedIndex].id);
        }
        break;
      case "Escape":
        e.preventDefault();
        setAddingToList(null);
        setItemSearch("");
        break;
    }
  };

  // Scroll highlighted item into view
  useEffect(() => {
    if (listRef.current) {
      const highlighted = listRef.current.querySelector(
        '[data-highlighted="true"]'
      );
      if (highlighted) {
        highlighted.scrollIntoView({ block: "nearest" });
      }
    }
  }, [highlightedIndex]);

  // Focus quantity input after adding an item
  useEffect(() => {
    if (focusedQtyItem) {
      const key = `${focusedQtyItem.keeplistId}-${focusedQtyItem.itemId}`;
      const input = qtyInputRefs.current.get(key);
      if (input) {
        input.focus();
        input.select();
      }
    }
  }, [focusedQtyItem]);

  // Handle keyboard on quantity input
  const handleQtyKeyDown = (
    e: React.KeyboardEvent<HTMLInputElement>,
    keeplistId: string,
    itemId: string,
    currentQty: number
  ) => {
    switch (e.key) {
      case "ArrowUp":
        e.preventDefault();
        updateItemQty(keeplistId, itemId, currentQty + 1);
        break;
      case "ArrowDown":
        e.preventDefault();
        updateItemQty(keeplistId, itemId, currentQty - 1);
        break;
      case "Enter":
        e.preventDefault();
        // Start adding another item to the same list
        setFocusedQtyItem(null);
        setAddingToList(keeplistId);
        setItemSearch("");
        setHighlightedIndex(0);
        // Focus will happen via autoFocus on the search input
        break;
      case "Escape":
        e.preventDefault();
        setFocusedQtyItem(null);
        (e.target as HTMLInputElement).blur();
        break;
    }
  };

  const toggleExpanded = (id: string) => {
    setExpandedLists((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const addKeeplist = () => {
    if (!newListName.trim()) return;
    const id = slugify(newListName);
    if (keeplists.some((kl) => kl.id === id)) {
      setCreateError("A keeplist with this name already exists");
      return;
    }
    setKeeplists((prev) => [
      ...prev,
      { id, name: newListName.trim(), isSystem: true, items: [] },
    ]);
    setExpandedLists((prev) => new Set([...prev, id]));
    setNewListName("");
    setCreateError(null);
  };

  const removeKeeplist = async (id: string, name: string) => {
    const confirmed = await confirm({
      title: "Remove Keeplist",
      message: `Remove "${name}" from the system keeplists?`,
      confirmLabel: "Remove",
      variant: "danger",
    });
    if (confirmed) {
      setKeeplists((prev) => prev.filter((kl) => kl.id !== id));
    }
  };

  const addItemToList = (keeplistId: string, itemId: string) => {
    setKeeplists((prev) =>
      prev.map((kl) => {
        if (kl.id !== keeplistId) return kl;
        if (kl.items.some((item) => item.itemId === itemId)) return kl;
        return {
          ...kl,
          items: [
            ...kl.items,
            { itemId, qtyOwned: 0, qtyRequired: 1, isCompleted: false },
          ],
        };
      })
    );
    // Close the search dropdown and focus the quantity input for the new item
    setAddingToList(null);
    setItemSearch("");
    // Use setTimeout to allow the DOM to update with the new item
    setTimeout(() => {
      setFocusedQtyItem({ keeplistId, itemId });
    }, 0);
  };

  const removeItemFromList = (keeplistId: string, itemId: string) => {
    setKeeplists((prev) =>
      prev.map((kl) => {
        if (kl.id !== keeplistId) return kl;
        return {
          ...kl,
          items: kl.items.filter((item) => item.itemId !== itemId),
        };
      })
    );
  };

  const updateItemQty = (
    keeplistId: string,
    itemId: string,
    qtyRequired: number
  ) => {
    setKeeplists((prev) =>
      prev.map((kl) => {
        if (kl.id !== keeplistId) return kl;
        return {
          ...kl,
          items: kl.items.map((item) =>
            item.itemId === itemId
              ? { ...item, qtyRequired: Math.max(1, qtyRequired) }
              : item
          ),
        };
      })
    );
  };

  const downloadFile = () => {
    const code = generateKeeplistsCode(keeplists);
    const blob = new Blob([code], { type: "text/typescript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "systemKeeplists.ts";
    a.click();
    URL.revokeObjectURL(url);
  };

  const writeFile = async () => {
    if (!isDev) return;

    setWriteStatus("Writing...");
    try {
      const code = generateKeeplistsCode(keeplists);
      const response = await fetch("/__dev/write-keeplists", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content: code }),
      });

      if (!response.ok) {
        throw new Error(await response.text());
      }

      setWriteStatus("Saved successfully!");
      setTimeout(() => setWriteStatus(null), 3000);
    } catch (err) {
      setWriteStatus(
        `Error: ${err instanceof Error ? err.message : "Failed to write"}`
      );
    }
  };

  const resetToDefault = async () => {
    const confirmed = await confirm({
      title: "Reset to Default",
      message: "Reset to the current systemKeeplists.ts? Unsaved changes will be lost.",
      confirmLabel: "Reset",
      variant: "warning",
    });
    if (confirmed) {
      setKeeplists(JSON.parse(JSON.stringify(systemKeeplists)));
    }
  };

  return (
    <div className="space-y-4">
      {/* Add new keeplist */}
      <div className="space-y-2">
        <div className="flex gap-2">
          <input
            type="text"
            value={newListName}
            onChange={(e) => {
              setNewListName(e.target.value);
              setCreateError(null);
            }}
            onKeyDown={(e) => e.key === "Enter" && addKeeplist()}
            placeholder="New keeplist name..."
            className={`flex-1 px-3 py-2 bg-slate-800 border rounded-lg text-slate-100 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-blue-500 ${
              createError ? "border-red-500" : "border-slate-700"
            }`}
          />
          <button
            onClick={addKeeplist}
            disabled={!newListName.trim()}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 disabled:bg-slate-700 disabled:text-slate-500 rounded-lg transition-colors"
          >
            <Plus className="w-4 h-4" />
            Add List
          </button>
        </div>
        {createError && (
          <p className="text-sm text-red-400">{createError}</p>
        )}
      </div>

      {/* Keeplists */}
      <div className="space-y-3">
        {keeplists.map((keeplist) => (
          <div
            key={keeplist.id}
            className="bg-slate-800 rounded-lg border border-slate-700 overflow-hidden"
          >
            {/* List header */}
            <div className="flex items-center gap-2 px-4 py-3 bg-slate-800/80">
              <button
                onClick={() => toggleExpanded(keeplist.id)}
                className="text-slate-400 hover:text-slate-200"
              >
                {expandedLists.has(keeplist.id) ? (
                  <ChevronDown className="w-5 h-5" />
                ) : (
                  <ChevronRight className="w-5 h-5" />
                )}
              </button>
              <span className="flex-1 font-medium">{keeplist.name}</span>
              <span className="text-sm text-slate-500">
                {keeplist.items.length} items
              </span>
              <button
                onClick={() => removeKeeplist(keeplist.id, keeplist.name)}
                className="p-1 text-slate-500 hover:text-red-400 transition-colors"
                title="Remove keeplist"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            </div>

            {/* List items */}
            {expandedLists.has(keeplist.id) && (
              <div className="px-4 pb-3 space-y-2">
                {keeplist.items.map((item) => {
                  const itemData = getItemByIdWithFallback(item.itemId);

                  return (
                    <div
                      key={item.itemId}
                      className="flex items-center gap-3 py-2 px-3 bg-slate-900/50 rounded-lg"
                    >
                      <span className="flex-1 text-sm">{itemData.name}</span>
                      <span
                        className={`text-xs px-2 py-0.5 rounded rarity-${itemData.rarity.toLowerCase()}`}
                      >
                        {itemData.rarity}
                      </span>
                      <div className="flex items-center gap-1">
                        <span className="text-xs text-slate-500">Qty:</span>
                        <input
                          ref={(el) => {
                            if (el) {
                              qtyInputRefs.current.set(
                                `${keeplist.id}-${item.itemId}`,
                                el
                              );
                            }
                          }}
                          type="number"
                          min="1"
                          value={item.qtyRequired}
                          onChange={(e) =>
                            updateItemQty(
                              keeplist.id,
                              item.itemId,
                              parseInt(e.target.value) || 1
                            )
                          }
                          onKeyDown={(e) =>
                            handleQtyKeyDown(
                              e,
                              keeplist.id,
                              item.itemId,
                              item.qtyRequired
                            )
                          }
                          onFocus={() =>
                            setFocusedQtyItem({
                              keeplistId: keeplist.id,
                              itemId: item.itemId,
                            })
                          }
                          onBlur={() => {
                            // Only clear if this is still the focused item
                            setFocusedQtyItem((prev) =>
                              prev?.keeplistId === keeplist.id &&
                              prev?.itemId === item.itemId
                                ? null
                                : prev
                            );
                          }}
                          className={`w-16 px-2 py-1 bg-slate-800 border rounded text-sm text-center transition-colors ${
                            focusedQtyItem?.keeplistId === keeplist.id &&
                            focusedQtyItem?.itemId === item.itemId
                              ? "border-blue-500 ring-1 ring-blue-500"
                              : "border-slate-700"
                          }`}
                        />
                      </div>
                      <button
                        onClick={() =>
                          removeItemFromList(keeplist.id, item.itemId)
                        }
                        className="p-1 text-slate-500 hover:text-red-400 transition-colors"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  );
                })}

                {/* Add item to list */}
                {addingToList === keeplist.id ? (
                  <div className="mt-2 p-3 bg-slate-900 rounded-lg border border-slate-600">
                    <div className="relative mb-2">
                      <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
                      <input
                        type="text"
                        value={itemSearch}
                        onChange={(e) => setItemSearch(e.target.value)}
                        onKeyDown={(e) => handleSearchKeyDown(e, keeplist.id)}
                        placeholder="Search... (↑↓ navigate, Enter select, Esc cancel)"
                        autoFocus
                        className="w-full pl-9 pr-3 py-2 bg-slate-800 border border-slate-700 rounded text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
                      />
                    </div>
                    <div
                      ref={listRef}
                      className="max-h-48 overflow-y-auto space-y-1"
                    >
                      {(() => {
                        let selectableIndex = 0;

                        return filteredItems.map((item) => {
                          const isDisabled = keeplist.items.some(
                            (i) => i.itemId === item.id
                          );
                          const currentSelectableIndex = isDisabled
                            ? -1
                            : selectableIndex++;
                          const isHighlighted =
                            !isDisabled &&
                            currentSelectableIndex === highlightedIndex;

                          return (
                            <button
                              key={item.id}
                              onClick={() =>
                                addItemToList(keeplist.id, item.id)
                              }
                              disabled={isDisabled}
                              data-highlighted={isHighlighted}
                              className={`w-full flex items-center gap-2 px-3 py-2 text-left text-sm rounded transition-colors ${
                                isHighlighted
                                  ? "bg-blue-600 text-white"
                                  : "hover:bg-slate-800"
                              } ${
                                isDisabled
                                  ? "opacity-50 cursor-not-allowed"
                                  : ""
                              }`}
                            >
                              <span className="flex-1">{item.name}</span>
                              <span
                                className={`text-xs ${
                                  isHighlighted
                                    ? "text-blue-200"
                                    : `rarity-${item.rarity.toLowerCase()}`
                                }`}
                              >
                                {item.rarity}
                              </span>
                            </button>
                          );
                        });
                      })()}
                    </div>
                    <div className="flex items-center justify-between mt-2">
                      <button
                        onClick={() => {
                          setAddingToList(null);
                          setItemSearch("");
                        }}
                        className="text-xs text-slate-500 hover:text-slate-300"
                      >
                        Cancel (Esc)
                      </button>
                      <span className="text-xs text-slate-600">
                        {getSelectableItems(keeplist.id).length} available
                      </span>
                    </div>
                  </div>
                ) : (
                  <button
                    onClick={() => setAddingToList(keeplist.id)}
                    className="w-full flex items-center justify-center gap-2 py-2 text-sm text-slate-500 hover:text-slate-300 hover:bg-slate-900/50 rounded-lg transition-colors"
                  >
                    <Plus className="w-4 h-4" />
                    Add Item
                  </button>
                )}
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Actions */}
      <div className="flex flex-wrap gap-3 pt-4 border-t border-slate-700">
        <button
          onClick={downloadFile}
          className="flex items-center gap-2 px-4 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg transition-colors"
        >
          <Download className="w-4 h-4" />
          Download systemKeeplists.ts
        </button>

        {isDev && (
          <button
            onClick={writeFile}
            className="flex items-center gap-2 px-4 py-2 bg-green-600 hover:bg-green-500 rounded-lg transition-colors"
          >
            <Save className="w-4 h-4" />
            Write to src/data/
          </button>
        )}

        <button
          onClick={resetToDefault}
          className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-400 rounded-lg transition-colors"
        >
          Reset to Current
        </button>

        {writeStatus && (
          <span
            className={`flex items-center text-sm ${
              writeStatus.startsWith("Error")
                ? "text-red-400"
                : writeStatus === "Writing..."
                ? "text-yellow-400"
                : "text-green-400"
            }`}
          >
            {writeStatus}
          </span>
        )}
      </div>

      {/* Help text */}
      <p className="text-xs text-slate-500">
        {isDev
          ? "In development mode, you can write directly to src/data/systemKeeplists.ts. Otherwise, download the file and replace it manually."
          : "Download the file and replace src/data/systemKeeplists.ts manually, then rebuild."}
      </p>

      {/* Confirm Dialog */}
      {dialogProps && <ConfirmDialog {...dialogProps} />}
    </div>
  );
}
