import { useState, useMemo, useEffect } from "react";
import {
  Plus,
  Trash2,
  Download,
  Save,
  ChevronDown,
  ChevronRight,
  Search,
} from "lucide-react";
import { systemKeeplists } from "../data/systemKeeplists";
import { dummyItems, getItemById } from "../data/dummyItems";
import type { Keeplist, RequiredItem } from "../types";

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function generateKeeplistsCode(keeplists: Keeplist[]): string {
  const itemsCode = keeplists
    .map((kl) => {
      const itemsStr = kl.items
        .map(
          (item) =>
            `      { itemId: "${item.itemId}", qtyOwned: 0, qtyRequired: ${item.qtyRequired}, isCompleted: false }`
        )
        .join(",\n");

      return `  {
    id: "${kl.id}",
    name: "${kl.name}",
    isSystem: true,
    items: [
${itemsStr},
    ],
  }`;
    })
    .join(",\n");

  return `import type { Keeplist } from "../types";

// System keeplists - default state provided by the app
// Generated by Keeplist Builder on ${new Date().toISOString()}
export const systemKeeplists: Keeplist[] = [
${itemsCode},
];
`;
}

export function KeeplistBuilder() {
  const [keeplists, setKeeplists] = useState<Keeplist[]>(() =>
    JSON.parse(JSON.stringify(systemKeeplists))
  );
  const [expandedLists, setExpandedLists] = useState<Set<string>>(
    new Set(systemKeeplists.map((kl) => kl.id))
  );
  const [itemSearch, setItemSearch] = useState("");
  const [addingToList, setAddingToList] = useState<string | null>(null);
  const [newListName, setNewListName] = useState("");
  const [writeStatus, setWriteStatus] = useState<string | null>(null);
  const [availableItems, setAvailableItems] = useState<RequiredItem[]>(dummyItems);

  const isDev = import.meta.env.DEV;

  // Try to load allItems.ts if it exists
  useEffect(() => {
    import("../data/allItems")
      .then((module) => {
        if (module.allItems && module.allItems.length > 0) {
          setAvailableItems(module.allItems);
        }
      })
      .catch(() => {
        // allItems.ts doesn't exist, keep using dummyItems
      });
  }, []);

  // Filter available items for adding
  const filteredItems = useMemo(() => {
    if (!itemSearch.trim()) return availableItems.slice(0, 20);
    const query = itemSearch.toLowerCase();
    return availableItems
      .filter((item) => item.name.toLowerCase().includes(query))
      .slice(0, 20);
  }, [itemSearch, availableItems]);

  const toggleExpanded = (id: string) => {
    setExpandedLists((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const addKeeperlist = () => {
    if (!newListName.trim()) return;
    const id = slugify(newListName);
    if (keeplists.some((kl) => kl.id === id)) {
      alert("A keeplist with this name already exists");
      return;
    }
    setKeeplists((prev) => [
      ...prev,
      { id, name: newListName.trim(), isSystem: true, items: [] },
    ]);
    setExpandedLists((prev) => new Set([...prev, id]));
    setNewListName("");
  };

  const removeKeeperlist = (id: string) => {
    if (!confirm("Remove this keeplist?")) return;
    setKeeplists((prev) => prev.filter((kl) => kl.id !== id));
  };

  const addItemToList = (keeplistId: string, itemId: string) => {
    setKeeplists((prev) =>
      prev.map((kl) => {
        if (kl.id !== keeplistId) return kl;
        if (kl.items.some((item) => item.itemId === itemId)) return kl;
        return {
          ...kl,
          items: [
            ...kl.items,
            { itemId, qtyOwned: 0, qtyRequired: 1, isCompleted: false },
          ],
        };
      })
    );
    setAddingToList(null);
    setItemSearch("");
  };

  const removeItemFromList = (keeplistId: string, itemId: string) => {
    setKeeplists((prev) =>
      prev.map((kl) => {
        if (kl.id !== keeplistId) return kl;
        return {
          ...kl,
          items: kl.items.filter((item) => item.itemId !== itemId),
        };
      })
    );
  };

  const updateItemQty = (
    keeplistId: string,
    itemId: string,
    qtyRequired: number
  ) => {
    setKeeplists((prev) =>
      prev.map((kl) => {
        if (kl.id !== keeplistId) return kl;
        return {
          ...kl,
          items: kl.items.map((item) =>
            item.itemId === itemId
              ? { ...item, qtyRequired: Math.max(1, qtyRequired) }
              : item
          ),
        };
      })
    );
  };

  const downloadFile = () => {
    const code = generateKeeplistsCode(keeplists);
    const blob = new Blob([code], { type: "text/typescript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "systemKeeplists.ts";
    a.click();
    URL.revokeObjectURL(url);
  };

  const writeFile = async () => {
    if (!isDev) return;

    setWriteStatus("Writing...");
    try {
      const code = generateKeeplistsCode(keeplists);
      const response = await fetch("/__dev/write-keeplists", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content: code }),
      });

      if (!response.ok) {
        throw new Error(await response.text());
      }

      setWriteStatus("Saved successfully!");
      setTimeout(() => setWriteStatus(null), 3000);
    } catch (err) {
      setWriteStatus(
        `Error: ${err instanceof Error ? err.message : "Failed to write"}`
      );
    }
  };

  const resetToDefault = () => {
    if (!confirm("Reset to the current systemKeeplists.ts? Unsaved changes will be lost.")) return;
    setKeeplists(JSON.parse(JSON.stringify(systemKeeplists)));
  };

  return (
    <div className="space-y-4">
      {/* Add new keeplist */}
      <div className="flex gap-2">
        <input
          type="text"
          value={newListName}
          onChange={(e) => setNewListName(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && addKeeperlist()}
          placeholder="New keeplist name..."
          className="flex-1 px-3 py-2 bg-slate-800 border border-slate-700 rounded-lg text-slate-100 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <button
          onClick={addKeeperlist}
          disabled={!newListName.trim()}
          className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 disabled:bg-slate-700 disabled:text-slate-500 rounded-lg transition-colors"
        >
          <Plus className="w-4 h-4" />
          Add List
        </button>
      </div>

      {/* Keeplists */}
      <div className="space-y-3">
        {keeplists.map((keeplist) => (
          <div
            key={keeplist.id}
            className="bg-slate-800 rounded-lg border border-slate-700 overflow-hidden"
          >
            {/* List header */}
            <div className="flex items-center gap-2 px-4 py-3 bg-slate-800/80">
              <button
                onClick={() => toggleExpanded(keeplist.id)}
                className="text-slate-400 hover:text-slate-200"
              >
                {expandedLists.has(keeplist.id) ? (
                  <ChevronDown className="w-5 h-5" />
                ) : (
                  <ChevronRight className="w-5 h-5" />
                )}
              </button>
              <span className="flex-1 font-medium">{keeplist.name}</span>
              <span className="text-sm text-slate-500">
                {keeplist.items.length} items
              </span>
              <button
                onClick={() => removeKeeperlist(keeplist.id)}
                className="p-1 text-slate-500 hover:text-red-400 transition-colors"
                title="Remove keeplist"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            </div>

            {/* List items */}
            {expandedLists.has(keeplist.id) && (
              <div className="px-4 pb-3 space-y-2">
                {keeplist.items.map((item) => {
                  const itemData = getItemById(item.itemId) ||
                    availableItems.find((i) => i.id === item.itemId) || {
                      id: item.itemId,
                      name: item.itemId,
                      rarity: "Common" as const,
                    };

                  return (
                    <div
                      key={item.itemId}
                      className="flex items-center gap-3 py-2 px-3 bg-slate-900/50 rounded-lg"
                    >
                      <span className="flex-1 text-sm">{itemData.name}</span>
                      <span
                        className={`text-xs px-2 py-0.5 rounded rarity-${itemData.rarity.toLowerCase()}`}
                      >
                        {itemData.rarity}
                      </span>
                      <div className="flex items-center gap-1">
                        <span className="text-xs text-slate-500">Qty:</span>
                        <input
                          type="number"
                          min="1"
                          value={item.qtyRequired}
                          onChange={(e) =>
                            updateItemQty(
                              keeplist.id,
                              item.itemId,
                              parseInt(e.target.value) || 1
                            )
                          }
                          className="w-16 px-2 py-1 bg-slate-800 border border-slate-700 rounded text-sm text-center"
                        />
                      </div>
                      <button
                        onClick={() =>
                          removeItemFromList(keeplist.id, item.itemId)
                        }
                        className="p-1 text-slate-500 hover:text-red-400 transition-colors"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  );
                })}

                {/* Add item to list */}
                {addingToList === keeplist.id ? (
                  <div className="mt-2 p-3 bg-slate-900 rounded-lg border border-slate-600">
                    <div className="relative mb-2">
                      <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
                      <input
                        type="text"
                        value={itemSearch}
                        onChange={(e) => setItemSearch(e.target.value)}
                        placeholder="Search items..."
                        autoFocus
                        className="w-full pl-9 pr-3 py-2 bg-slate-800 border border-slate-700 rounded text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
                      />
                    </div>
                    <div className="max-h-48 overflow-y-auto space-y-1">
                      {filteredItems.map((item) => (
                        <button
                          key={item.id}
                          onClick={() => addItemToList(keeplist.id, item.id)}
                          disabled={keeplist.items.some(
                            (i) => i.itemId === item.id
                          )}
                          className="w-full flex items-center gap-2 px-3 py-2 text-left text-sm rounded hover:bg-slate-800 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        >
                          <span className="flex-1">{item.name}</span>
                          <span
                            className={`text-xs rarity-${item.rarity.toLowerCase()}`}
                          >
                            {item.rarity}
                          </span>
                        </button>
                      ))}
                    </div>
                    <button
                      onClick={() => {
                        setAddingToList(null);
                        setItemSearch("");
                      }}
                      className="mt-2 text-xs text-slate-500 hover:text-slate-300"
                    >
                      Cancel
                    </button>
                  </div>
                ) : (
                  <button
                    onClick={() => setAddingToList(keeplist.id)}
                    className="w-full flex items-center justify-center gap-2 py-2 text-sm text-slate-500 hover:text-slate-300 hover:bg-slate-900/50 rounded-lg transition-colors"
                  >
                    <Plus className="w-4 h-4" />
                    Add Item
                  </button>
                )}
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Actions */}
      <div className="flex flex-wrap gap-3 pt-4 border-t border-slate-700">
        <button
          onClick={downloadFile}
          className="flex items-center gap-2 px-4 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg transition-colors"
        >
          <Download className="w-4 h-4" />
          Download systemKeeplists.ts
        </button>

        {isDev && (
          <button
            onClick={writeFile}
            className="flex items-center gap-2 px-4 py-2 bg-green-600 hover:bg-green-500 rounded-lg transition-colors"
          >
            <Save className="w-4 h-4" />
            Write to src/data/
          </button>
        )}

        <button
          onClick={resetToDefault}
          className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-400 rounded-lg transition-colors"
        >
          Reset to Current
        </button>

        {writeStatus && (
          <span
            className={`flex items-center text-sm ${
              writeStatus.startsWith("Error")
                ? "text-red-400"
                : writeStatus === "Writing..."
                ? "text-yellow-400"
                : "text-green-400"
            }`}
          >
            {writeStatus}
          </span>
        )}
      </div>

      {/* Help text */}
      <p className="text-xs text-slate-500">
        {isDev
          ? 'In development mode, you can write directly to src/data/systemKeeplists.ts. Otherwise, download the file and replace it manually.'
          : 'Download the file and replace src/data/systemKeeplists.ts manually, then rebuild.'}
      </p>
    </div>
  );
}
