// Auto-generated by scripts/fetch-items.ts
// Last updated: 2026-01-07T13:04:05.142Z
// Source: https://metaforge.app/api/arc-raiders/items

import type { RequiredItem } from "../types";

export const allItems: RequiredItem[] = [
  {
    "id": "acoustic-guitar",
    "name": "Acoustic Guitar",
    "rarity": "Legendary"
  },
  {
    "id": "adrenaline-shot",
    "name": "Adrenaline Shot",
    "rarity": "Common"
  },
  {
    "id": "advanced-arc-powercell",
    "name": "Advanced ARC Powercell",
    "rarity": "Rare"
  },
  {
    "id": "advanced-electrical-components",
    "name": "Advanced Electrical Components",
    "rarity": "Rare"
  },
  {
    "id": "advanced-mechanical-components",
    "name": "Advanced Mechanical Components",
    "rarity": "Rare"
  },
  {
    "id": "agave",
    "name": "Agave",
    "rarity": "Common"
  },
  {
    "id": "agave-juice",
    "name": "Agave Juice",
    "rarity": "Common"
  },
  {
    "id": "air-freshener",
    "name": "Air Freshener",
    "rarity": "Uncommon"
  },
  {
    "id": "alarm-clock",
    "name": "Alarm Clock",
    "rarity": "Rare"
  },
  {
    "id": "angled-grip-i",
    "name": "Angled Grip I",
    "rarity": "Common"
  },
  {
    "id": "angled-grip-ii",
    "name": "Angled Grip II",
    "rarity": "Uncommon"
  },
  {
    "id": "angled-grip-ii-recipe",
    "name": "Angled Grip II Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "angled-grip-iii",
    "name": "Angled Grip III",
    "rarity": "Rare"
  },
  {
    "id": "angled-grip-iii-recipe",
    "name": "Angled Grip III Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "antiseptic",
    "name": "Antiseptic",
    "rarity": "Rare"
  },
  {
    "id": "anvil-recipe",
    "name": "Anvil Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "anvil-i",
    "name": "Anvil I",
    "rarity": "Uncommon"
  },
  {
    "id": "anvil-ii",
    "name": "Anvil II",
    "rarity": "Uncommon"
  },
  {
    "id": "anvil-iii",
    "name": "Anvil III",
    "rarity": "Uncommon"
  },
  {
    "id": "anvil-iv",
    "name": "Anvil IV",
    "rarity": "Uncommon"
  },
  {
    "id": "anvil-splitter",
    "name": "Anvil Splitter",
    "rarity": "Legendary"
  },
  {
    "id": "aphelion-rifle",
    "name": "Aphelion Rifle",
    "rarity": "Legendary"
  },
  {
    "id": "aphelion-rifle-blueprint",
    "name": "Aphelion Rifle Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "apricot",
    "name": "Apricot",
    "rarity": "Common"
  },
  {
    "id": "arc-alloy",
    "name": "ARC Alloy",
    "rarity": "Uncommon"
  },
  {
    "id": "arc-circuitry",
    "name": "ARC Circuitry",
    "rarity": "Rare"
  },
  {
    "id": "arc-coolant",
    "name": "ARC Coolant",
    "rarity": "Rare"
  },
  {
    "id": "arc-flex-rubber",
    "name": "ARC Flex Rubber",
    "rarity": "Rare"
  },
  {
    "id": "arc-motion-core",
    "name": "ARC Motion Core",
    "rarity": "Rare"
  },
  {
    "id": "arc-performance-steel",
    "name": "ARC Performance Steel",
    "rarity": "Rare"
  },
  {
    "id": "arc-powercell",
    "name": "ARC Powercell",
    "rarity": "Common"
  },
  {
    "id": "arc-synthetic-resin",
    "name": "ARC Synthetic Resin",
    "rarity": "Rare"
  },
  {
    "id": "arc-thermo-lining",
    "name": "ARC Thermo Lining",
    "rarity": "Rare"
  },
  {
    "id": "arpeggio-i",
    "name": "Arpeggio I",
    "rarity": "Uncommon"
  },
  {
    "id": "arpeggio-ii",
    "name": "Arpeggio II",
    "rarity": "Uncommon"
  },
  {
    "id": "arpeggio-iii",
    "name": "Arpeggio III",
    "rarity": "Uncommon"
  },
  {
    "id": "arpeggio-iv",
    "name": "Arpeggio IV",
    "rarity": "Uncommon"
  },
  {
    "id": "assorted-seeds",
    "name": "Assorted Seeds",
    "rarity": "Common"
  },
  {
    "id": "aviator-outfit",
    "name": "Aviator (Outfit)",
    "rarity": "Common"
  },
  {
    "id": "bag-radio-renegade-variant",
    "name": "Bag (Radio Renegade Variant)",
    "rarity": "Common"
  },
  {
    "id": "banana-backpack-charm",
    "name": "Banana (Backpack Charm)",
    "rarity": "Common"
  },
  {
    "id": "bandage",
    "name": "Bandage",
    "rarity": "Common"
  },
  {
    "id": "barricade-kit",
    "name": "Barricade Kit",
    "rarity": "Uncommon"
  },
  {
    "id": "barricade-kit-recipe",
    "name": "Barricade Kit Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "bastion-part",
    "name": "Bastion Cell",
    "rarity": "Epic"
  },
  {
    "id": "battery",
    "name": "Battery",
    "rarity": "Uncommon"
  },
  {
    "id": "bettina-blueprint",
    "name": "Bettina Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "bettina-i",
    "name": "Bettina I",
    "rarity": "Epic"
  },
  {
    "id": "bettina-ii",
    "name": "Bettina II",
    "rarity": "Epic"
  },
  {
    "id": "bettina-iii",
    "name": "Bettina III",
    "rarity": "Epic"
  },
  {
    "id": "bettina-iv",
    "name": "Bettina IV",
    "rarity": "Epic"
  },
  {
    "id": "bicycle-pump",
    "name": "Bicycle Pump",
    "rarity": "Rare"
  },
  {
    "id": "binoculars",
    "name": "Binoculars",
    "rarity": "Common"
  },
  {
    "id": "bison-driver",
    "name": "Bison Driver",
    "rarity": "Rare"
  },
  {
    "id": "black-eye-face-style",
    "name": "Black Eye (Face Style)",
    "rarity": "Common"
  },
  {
    "id": "black-hiker-colour",
    "name": "Black (Hiker Colour)",
    "rarity": "Common"
  },
  {
    "id": "black-and-white-origin-color",
    "name": "Black & White (Origin Color)",
    "rarity": "Common"
  },
  {
    "id": "blaze-grenade",
    "name": "Blaze Grenade",
    "rarity": "Rare"
  },
  {
    "id": "blaze-grenade-blueprint",
    "name": "Blaze Grenade Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "blaze-grenade-trap",
    "name": "Blaze Grenade Trap",
    "rarity": "Rare"
  },
  {
    "id": "bloated-tuna-can",
    "name": "Bloated Tuna Can",
    "rarity": "Common"
  },
  {
    "id": "blue-gate-cellar-key",
    "name": "Blue Gate Cellar Key",
    "rarity": "Rare"
  },
  {
    "id": "blue-gate-communication-tower-key",
    "name": "Blue Gate Communication Tower Key",
    "rarity": "Rare"
  },
  {
    "id": "blue-gate-confiscation-room-key",
    "name": "Blue Gate Confiscation Room Key",
    "rarity": "Epic"
  },
  {
    "id": "blue-gate-village-key",
    "name": "Blue Gate Village Key",
    "rarity": "Rare"
  },
  {
    "id": "blue-light-stick",
    "name": "Blue Light Stick",
    "rarity": "Common"
  },
  {
    "id": "blue-light-stick-blueprint",
    "name": "Blue Light Stick Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "blue-radio-renegade-color",
    "name": "Blue (Radio Renegade Color)",
    "rarity": "Common"
  },
  {
    "id": "blue-yellow-aviator-color",
    "name": "Blue Yellow (Aviator Color)",
    "rarity": "Common"
  },
  {
    "id": "bobcat-i-recipe",
    "name": "Bobcat Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "bobcat-i",
    "name": "Bobcat I",
    "rarity": "Epic"
  },
  {
    "id": "bobcat-ii",
    "name": "Bobcat II",
    "rarity": "Epic"
  },
  {
    "id": "bobcat-iii",
    "name": "Bobcat III",
    "rarity": "Epic"
  },
  {
    "id": "bobcat-iv",
    "name": "Bobcat IV",
    "rarity": "Epic"
  },
  {
    "id": "bombardier-cell",
    "name": "Bombardier Cell",
    "rarity": "Epic"
  },
  {
    "id": "bow-and-arrow-emote",
    "name": "Bow and Arrow (Emote)",
    "rarity": "Common"
  },
  {
    "id": "breathtaking-snow-globe",
    "name": "Breathtaking Snow Globe",
    "rarity": "Epic"
  },
  {
    "id": "briefcase-backpack-attachment",
    "name": "Briefcase (Backpack Attachment)",
    "rarity": "Common"
  },
  {
    "id": "broken-flashlight",
    "name": "Broken Flashlight",
    "rarity": "Rare"
  },
  {
    "id": "broken-guidance-system",
    "name": "Broken Guidance System",
    "rarity": "Rare"
  },
  {
    "id": "broken-handcuffs",
    "name": "Broken Handcuffs",
    "rarity": "Uncommon"
  },
  {
    "id": "broken-handheld-radio",
    "name": "Broken Handheld Radio",
    "rarity": "Rare"
  },
  {
    "id": "broken-riot-shield",
    "name": "Broken Riot Shield",
    "rarity": "Rare"
  },
  {
    "id": "broken-taser",
    "name": "Broken Taser",
    "rarity": "Rare"
  },
  {
    "id": "burgerboy-backpack-charm",
    "name": "Burgerboy (Backpack Charm)",
    "rarity": "Common"
  },
  {
    "id": "buried-city-hospital-key",
    "name": "Buried City Hospital Key",
    "rarity": "Rare"
  },
  {
    "id": "buried-city-jkv-employee-access-card",
    "name": "Buried City JKV Employee Access Card",
    "rarity": "Uncommon"
  },
  {
    "id": "buried-city-residential-master-key",
    "name": "Buried City Residential Master Key",
    "rarity": "Uncommon"
  },
  {
    "id": "buried-city-town-hall-key",
    "name": "Buried City Town Hall Key",
    "rarity": "Epic"
  },
  {
    "id": "burltetta-recipe",
    "name": "Burletta Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "burletta-i",
    "name": "Burletta I",
    "rarity": "Uncommon"
  },
  {
    "id": "burletta-ii",
    "name": "Burletta II",
    "rarity": "Uncommon"
  },
  {
    "id": "burletta-iiii",
    "name": "Burletta III",
    "rarity": "Uncommon"
  },
  {
    "id": "burletta-iv",
    "name": "Burletta IV",
    "rarity": "Uncommon"
  },
  {
    "id": "burned-arc-circuitry",
    "name": "Burned ARC Circuitry",
    "rarity": "Uncommon"
  },
  {
    "id": "burnt-out-candles",
    "name": "Burnt-Out Candles",
    "rarity": "Common"
  },
  {
    "id": "camera-lens",
    "name": "Camera Lens",
    "rarity": "Uncommon"
  },
  {
    "id": "candleberries",
    "name": "Candleberries",
    "rarity": "Rare"
  },
  {
    "id": "candle-holder",
    "name": "Candle Holder",
    "rarity": "Uncommon"
  },
  {
    "id": "canister",
    "name": "Canister",
    "rarity": "Uncommon"
  },
  {
    "id": "cans-backpack-attachment",
    "name": "Cans (Backpack Attachment)",
    "rarity": "Common"
  },
  {
    "id": "cat-bed",
    "name": "Cat Bed",
    "rarity": "Uncommon"
  },
  {
    "id": "cheer-emote",
    "name": "Cheer (Emote)",
    "rarity": "Common"
  },
  {
    "id": "chemicals",
    "name": "Chemicals",
    "rarity": "Common"
  },
  {
    "id": "coffee-pot",
    "name": "Coffee Pot",
    "rarity": "Common"
  },
  {
    "id": "combat-mk-1",
    "name": "Combat Mk. 1",
    "rarity": "Uncommon"
  },
  {
    "id": "combat-mk-2",
    "name": "Combat Mk. 2",
    "rarity": "Rare"
  },
  {
    "id": "combat-mk-3-aggressive",
    "name": "Combat Mk. 3 (Aggressive)",
    "rarity": "Epic"
  },
  {
    "id": "combat-mk3-aggressive-blueprint",
    "name": "Combat Mk.3 (Aggressive) Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "combat-mk3-flanking",
    "name": "Combat Mk.3 (Flanking) ",
    "rarity": "Epic"
  },
  {
    "id": "combat-mk-3-flanking",
    "name": "Combat Mk. 3 (Flanking) Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "compensator-i",
    "name": "Compensator I",
    "rarity": "Common"
  },
  {
    "id": "compensator-ii",
    "name": "Compensator II",
    "rarity": "Uncommon"
  },
  {
    "id": "compensator-ii-recipe",
    "name": "Compensator II Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "compensator-iii",
    "name": "Compensator III",
    "rarity": "Rare"
  },
  {
    "id": "compensator-iii-recipe",
    "name": "Compensator III Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "complex-gun-parts",
    "name": "Complex Gun Parts",
    "rarity": "Epic"
  },
  {
    "id": "complex-gun-parts-blueprint",
    "name": "Complex Gun Parts Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "coolant",
    "name": "Coolant",
    "rarity": "Rare"
  },
  {
    "id": "cooling-coil",
    "name": "Cooling Coil",
    "rarity": "Rare"
  },
  {
    "id": "cooling-fan",
    "name": "Cooling Fan",
    "rarity": "Rare"
  },
  {
    "id": "cracked-bioscanner",
    "name": "Cracked Bioscanner",
    "rarity": "Rare"
  },
  {
    "id": "crimson-racer-aviator-colour",
    "name": "Crimson Racer (Aviator Colour)",
    "rarity": "Common"
  },
  {
    "id": "crude-explosives",
    "name": "Crude Explosives",
    "rarity": "Uncommon"
  },
  {
    "id": "crumpled-plastic-bottle",
    "name": "Crumpled Plastic Bottle",
    "rarity": "Uncommon"
  },
  {
    "id": "damaged-arc-motion-core",
    "name": "Damaged ARC Motion Core",
    "rarity": "Uncommon"
  },
  {
    "id": "damaged-arc-powercell",
    "name": "Damaged ARC Powercell",
    "rarity": "Common"
  },
  {
    "id": "damaged-fireball-burner",
    "name": "Damaged Fireball Burner",
    "rarity": "Common"
  },
  {
    "id": "damaged-heat-sink",
    "name": "Damaged Heat Sink",
    "rarity": "Rare"
  },
  {
    "id": "danaged-hornet-driver",
    "name": "Damaged Hornet Driver",
    "rarity": "Common"
  },
  {
    "id": "damaged-rocketeer-part",
    "name": "Damaged Rocketeer Driver",
    "rarity": "Common"
  },
  {
    "id": "damaged-tick-pod",
    "name": "Damaged Tick Pod",
    "rarity": "Common"
  },
  {
    "id": "damaged-wasp-driver",
    "name": "Damaged Wasp Driver",
    "rarity": "Common"
  },
  {
    "id": "dam-control-center-tower-key",
    "name": "Dam Control Center Tower Key",
    "rarity": "Epic"
  },
  {
    "id": "dam-staff-room-key",
    "name": "Dam Staff Room Key",
    "rarity": "Uncommon"
  },
  {
    "id": "dam-surveillance-key",
    "name": "Dam Surveillance Key",
    "rarity": "Uncommon"
  },
  {
    "id": "dam-testing-annex-key",
    "name": "Dam Testing Annex Key",
    "rarity": "Rare"
  },
  {
    "id": "dam-utility-key",
    "name": "Dam Utility Key",
    "rarity": "Uncommon"
  },
  {
    "id": "dart-board",
    "name": "Dart Board",
    "rarity": "Uncommon"
  },
  {
    "id": "deadline",
    "name": "Deadline",
    "rarity": "Epic"
  },
  {
    "id": "deadline-blueprint",
    "name": "Deadline Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "defibrillator",
    "name": "Defibrillator",
    "rarity": "Rare"
  },
  {
    "id": "defibrillator-recipe",
    "name": "Defibrillator Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "deflated-football",
    "name": "Deflated Football",
    "rarity": "Uncommon"
  },
  {
    "id": "degraded-arc-rubber",
    "name": "Degraded ARC Rubber",
    "rarity": "Uncommon"
  },
  {
    "id": "diving-googles",
    "name": "Diving Goggles",
    "rarity": "Rare"
  },
  {
    "id": "dog-collar",
    "name": "Dog Collar",
    "rarity": "Rare"
  },
  {
    "id": "door-blocker",
    "name": "Door Blocker",
    "rarity": "Common"
  },
  {
    "id": "dried-out-arc-resin",
    "name": "Dried-Out ARC Resin",
    "rarity": "Uncommon"
  },
  {
    "id": "duct-tape-recipe",
    "name": "Duct Tape",
    "rarity": "Uncommon"
  },
  {
    "id": "durable-cloth",
    "name": "Durable Cloth",
    "rarity": "Uncommon"
  },
  {
    "id": "electrical-components",
    "name": "Electrical Components",
    "rarity": "Uncommon"
  },
  {
    "id": "empty-wine-bottle",
    "name": "Empty Wine Bottle",
    "rarity": "Common"
  },
  {
    "id": "energy-ammo",
    "name": "Energy Clip",
    "rarity": "Rare"
  },
  {
    "id": "equalizer-i",
    "name": "Equalizer",
    "rarity": "Legendary"
  },
  {
    "id": "equalizer-recipe",
    "name": "Equalizer Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "esr-analyzer",
    "name": "ESR Analyzer",
    "rarity": "Common"
  },
  {
    "id": "exodus-modules",
    "name": "Exodus Modules",
    "rarity": "Epic"
  },
  {
    "id": "expired-pasta",
    "name": "Expired Pasta",
    "rarity": "Common"
  },
  {
    "id": "expired-respirator",
    "name": "Expired Respirator",
    "rarity": "Rare"
  },
  {
    "id": "explosive-compound",
    "name": "Explosive Compound",
    "rarity": "Rare"
  },
  {
    "id": "explosive-mine",
    "name": "Explosive Mine",
    "rarity": "Rare"
  },
  {
    "id": "explosive-mine-blueprint",
    "name": "Explosive Mine Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "extended-barrel",
    "name": "Extended Barrel",
    "rarity": "Epic"
  },
  {
    "id": "extended-barrel-recipe",
    "name": "Extended Barrel Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "extended-light-mag-i",
    "name": "Extended Light Mag I",
    "rarity": "Common"
  },
  {
    "id": "extended-light-mag-ii",
    "name": "Extended Light Mag II",
    "rarity": "Uncommon"
  },
  {
    "id": "extended-light-mag-ii-recipe",
    "name": "Extended Light Mag II Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "extended-light-mag-iii",
    "name": "Extended Light Mag III",
    "rarity": "Rare"
  },
  {
    "id": "extended-light-mag-iii-recipe",
    "name": "Extended Light Mag III Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "extended-medium-mag-i",
    "name": "Extended Medium Mag I",
    "rarity": "Common"
  },
  {
    "id": "extended-medium-mag-ii",
    "name": "Extended Medium Mag II",
    "rarity": "Uncommon"
  },
  {
    "id": "extended-medium-mag-ii-recipe",
    "name": "Extended Medium Mag II Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "extended-medium-mag-iii",
    "name": "Extended Medium Mag III",
    "rarity": "Rare"
  },
  {
    "id": "extended-medium-mag-iii-blueprint",
    "name": "Extended Medium Mag III Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "extended-shotgun-mag-i",
    "name": "Extended Shotgun Mag I",
    "rarity": "Common"
  },
  {
    "id": "extended-shotgun-mag-ii",
    "name": "Extended Shotgun Mag II",
    "rarity": "Uncommon"
  },
  {
    "id": "extended-shotgun-mag-ii-recipe",
    "name": "Extended Shotgun Mag II Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "extended-shotgun-mag-iii",
    "name": "Extended Shotgun Mag III",
    "rarity": "Rare"
  },
  {
    "id": "extended-shotgun-mag-iii-recipe",
    "name": "Extended Shotgun Mag III Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "fabric",
    "name": "Fabric",
    "rarity": "Common"
  },
  {
    "id": "faded-photograph",
    "name": "Faded Photograph",
    "rarity": "Common"
  },
  {
    "id": "ferro-i",
    "name": "Ferro I",
    "rarity": "Common"
  },
  {
    "id": "ferro-ii",
    "name": "Ferro II",
    "rarity": "Common"
  },
  {
    "id": "ferro-iii",
    "name": "Ferro III",
    "rarity": "Common"
  },
  {
    "id": "ferro-iv",
    "name": "Ferro IV",
    "rarity": "Common"
  },
  {
    "id": "fertilizer",
    "name": "Fertilizer",
    "rarity": "Common"
  },
  {
    "id": "film-reel",
    "name": "Film Reel",
    "rarity": "Rare"
  },
  {
    "id": "fine-wristwatch",
    "name": "Fine Wristwatch",
    "rarity": "Rare"
  },
  {
    "id": "fireball-burner",
    "name": "Fireball Burner",
    "rarity": "Uncommon"
  },
  {
    "id": "firecracker",
    "name": "Firecracker",
    "rarity": "Common"
  },
  {
    "id": "fireworks-box",
    "name": "Fireworks Box",
    "rarity": "Rare"
  },
  {
    "id": "fireworks-box-blueprint",
    "name": "Fireworks Box Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "flame-spray",
    "name": "Flame Spray",
    "rarity": "Uncommon"
  },
  {
    "id": "flow-controller",
    "name": "Flow Controller",
    "rarity": "Rare"
  },
  {
    "id": "flushing-terminal-key",
    "name": "Flushing Terminal Key",
    "rarity": "Common"
  },
  {
    "id": "fossilized-lightning",
    "name": "Fossilized Lightning",
    "rarity": "Epic"
  },
  {
    "id": "free-loadout-augment",
    "name": "Free Loadout Augment",
    "rarity": "Common"
  },
  {
    "id": "frequency-modulation-box",
    "name": "Frequency Modulation Box",
    "rarity": "Rare"
  },
  {
    "id": "fried-motherboard",
    "name": "Fried Motherboard",
    "rarity": "Rare"
  },
  {
    "id": "fruit-mix",
    "name": "Fruit Mix",
    "rarity": "Common"
  },
  {
    "id": "frying-pan",
    "name": "Frying Pan",
    "rarity": "Rare"
  },
  {
    "id": "garlic-press",
    "name": "Garlic Press",
    "rarity": "Uncommon"
  },
  {
    "id": "gas-grenade",
    "name": "Gas Grenade",
    "rarity": "Common"
  },
  {
    "id": "gas-grenade-trap",
    "name": "Gas Grenade Trap",
    "rarity": "Common"
  },
  {
    "id": "gas-mine",
    "name": "Gas Mine",
    "rarity": "Common"
  },
  {
    "id": "gas-mine-blueprint",
    "name": "Gas Mine Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "geiger-counter",
    "name": "Geiger Counter",
    "rarity": "Epic"
  },
  {
    "id": "goggles-radio-renegade-variant",
    "name": "Goggles (Radio Renegade Variant)",
    "rarity": "Common"
  },
  {
    "id": "great-muullein",
    "name": "Great Mullein",
    "rarity": "Uncommon"
  },
  {
    "id": "green-light-stick",
    "name": "Green Light Stick",
    "rarity": "Common"
  },
  {
    "id": "green-light-stick-blueprint",
    "name": "Green Light Stick Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "hairpin-i",
    "name": "Hairpin I",
    "rarity": "Common"
  },
  {
    "id": "hairpin-ii",
    "name": "Hairpin II",
    "rarity": "Common"
  },
  {
    "id": "hairpin-iii",
    "name": "Hairpin III",
    "rarity": "Common"
  },
  {
    "id": "hairpin-iv",
    "name": "Hairpin IV",
    "rarity": "Common"
  },
  {
    "id": "happy-jig-emote",
    "name": "Happy Jig (Emote)",
    "rarity": "Common"
  },
  {
    "id": "headphones",
    "name": "Headphones",
    "rarity": "Rare"
  },
  {
    "id": "heavy-ammo",
    "name": "Heavy Ammo",
    "rarity": "Common"
  },
  {
    "id": "heavy-fuze-grenade",
    "name": "Heavy Fuze Grenade",
    "rarity": "Rare"
  },
  {
    "id": "heavy-gun-parts",
    "name": "Heavy Gun Parts",
    "rarity": "Rare"
  },
  {
    "id": "heavy-gun-parts-recipe",
    "name": "Heavy Gun Parts Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "heavy-shield",
    "name": "Heavy Shield",
    "rarity": "Epic"
  },
  {
    "id": "helmet-radio-renegade-variant",
    "name": "Helmet (Radio Renegade Variant)",
    "rarity": "Common"
  },
  {
    "id": "herbal-bandage",
    "name": "Herbal Bandage",
    "rarity": "Uncommon"
  },
  {
    "id": "horizontal-grip",
    "name": "Horizontal Grip",
    "rarity": "Epic"
  },
  {
    "id": "hornet-driver",
    "name": "Hornet Driver",
    "rarity": "Rare"
  },
  {
    "id": "household-cleaner",
    "name": "Household Cleaner",
    "rarity": "Uncommon"
  },
  {
    "id": "hullcracker-blueprint",
    "name": "Hullcracker Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "hullcracker-i",
    "name": "Hullcracker I",
    "rarity": "Epic"
  },
  {
    "id": "hullcracker-ii",
    "name": "Hullcracker II",
    "rarity": "Epic"
  },
  {
    "id": "hullcracker-iii",
    "name": "Hullcracker III",
    "rarity": "Epic"
  },
  {
    "id": "hullcracker-iv",
    "name": "Hullcracker IV ",
    "rarity": "Epic"
  },
  {
    "id": "humidifier",
    "name": "Humidifier",
    "rarity": "Rare"
  },
  {
    "id": "ice-cream-scooper",
    "name": "Ice Cream Scooper",
    "rarity": "Uncommon"
  },
  {
    "id": "il-toro-recipe",
    "name": "Il Toro Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "il-toro-i",
    "name": "Il Toro I",
    "rarity": "Uncommon"
  },
  {
    "id": "il-toro-ii",
    "name": "Il Toro II",
    "rarity": "Uncommon"
  },
  {
    "id": "il-toro-iiii",
    "name": "Il Toro III",
    "rarity": "Uncommon"
  },
  {
    "id": "il-toro-iv",
    "name": "Il Toro IV",
    "rarity": "Uncommon"
  },
  {
    "id": "impure-arc-coolant",
    "name": "Impure ARC Coolant",
    "rarity": "Uncommon"
  },
  {
    "id": "industrial-battery",
    "name": "Industrial Battery",
    "rarity": "Rare"
  },
  {
    "id": "industrial-charger",
    "name": "Industrial Charger",
    "rarity": "Rare"
  },
  {
    "id": "industrial-magnet",
    "name": "Industrial Magnet",
    "rarity": "Rare"
  },
  {
    "id": "ion-sputter",
    "name": "Ion Sputter",
    "rarity": "Epic"
  },
  {
    "id": "jolt-mine",
    "name": "Jolt Mine",
    "rarity": "Rare"
  },
  {
    "id": "jolt-mine-recipe",
    "name": "Jolt Mine Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "junior-outfit",
    "name": "Junior (Outfit)",
    "rarity": "Common"
  },
  {
    "id": "jupiter-i",
    "name": "Jupiter",
    "rarity": "Legendary"
  },
  {
    "id": "jupiter-i-recipe",
    "name": "Jupiter Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "kettle-i",
    "name": "Kettle I",
    "rarity": "Common"
  },
  {
    "id": "kettle-ii",
    "name": "Kettle II",
    "rarity": "Common"
  },
  {
    "id": "kettle-iii",
    "name": "Kettle III",
    "rarity": "Common"
  },
  {
    "id": "kettle-iv",
    "name": "Kettle IV",
    "rarity": "Common"
  },
  {
    "id": "kinetic-converter",
    "name": "Kinetic Converter",
    "rarity": "Legendary"
  },
  {
    "id": "laboratory-reagents",
    "name": "Laboratory Reagents",
    "rarity": "Rare"
  },
  {
    "id": "lances-mixtape-5th-edition",
    "name": "Lance's Mixtape (5th Edition)",
    "rarity": "Epic"
  },
  {
    "id": "laser-trap-lure-recipe",
    "name": "Laser Trap: Lure",
    "rarity": "Common"
  },
  {
    "id": "launcher-ammo",
    "name": "Launcher Ammo",
    "rarity": "Rare"
  },
  {
    "id": "leaper-pulse-unit",
    "name": "Leaper Pulse Unit",
    "rarity": "Epic"
  },
  {
    "id": "lemon",
    "name": "Lemon",
    "rarity": "Common"
  },
  {
    "id": "lidar-scanner",
    "name": "Lidar Scanner",
    "rarity": "Common"
  },
  {
    "id": "light-ammo",
    "name": "Light Ammo",
    "rarity": "Common"
  },
  {
    "id": "light-bulb",
    "name": "Light Bulb",
    "rarity": "Uncommon"
  },
  {
    "id": "light-gun-parts",
    "name": "Light Gun Parts",
    "rarity": "Rare"
  },
  {
    "id": "light-gun-parts-recipe",
    "name": "Light Gun Parts Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "light-impact-grenade",
    "name": "Light Impact Grenade",
    "rarity": "Common"
  },
  {
    "id": "light-shield",
    "name": "Light Shield",
    "rarity": "Uncommon"
  },
  {
    "id": "lightweight-stock",
    "name": "Lightweight Stock",
    "rarity": "Epic"
  },
  {
    "id": "lightweight-stock-recipe",
    "name": "Lightweight Stock Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "lil-smoke-grenade",
    "name": "Li'l Smoke Grenade",
    "rarity": "Common"
  },
  {
    "id": "looting-mk-1",
    "name": "Looting Mk. 1",
    "rarity": "Uncommon"
  },
  {
    "id": "looting-mk-2",
    "name": "Looting Mk. 2",
    "rarity": "Rare"
  },
  {
    "id": "looting-mk-3-cautious",
    "name": "Looting MK. 3 (Cautious)",
    "rarity": "Epic"
  },
  {
    "id": "looting-mk-3-survivor",
    "name": "Looting MK. 3 (Survivor)",
    "rarity": "Epic"
  },
  {
    "id": "looting-mk-3-survivor-blueprint",
    "name": "Looting MK. 3 (Survivor) Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "lure-grenade",
    "name": "Lure Grenade",
    "rarity": "Uncommon"
  },
  {
    "id": "lure-grenade-recipe",
    "name": "Lure Grenade Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "lure-grenade-trap",
    "name": "Lure Grenade Trap",
    "rarity": "Uncommon"
  },
  {
    "id": "magnet",
    "name": "Magnet",
    "rarity": "Uncommon"
  },
  {
    "id": "magnetic-accelerator",
    "name": "Magnetic Accelerator",
    "rarity": "Epic"
  },
  {
    "id": "magnetron",
    "name": "Magnetron",
    "rarity": "Epic"
  },
  {
    "id": "mastery-medal-backpack-charm",
    "name": "Mastery Medal (Backpack Charm)",
    "rarity": "Common"
  },
  {
    "id": "matriarch-reactor",
    "name": "Matriarch Reactor",
    "rarity": "Legendary"
  },
  {
    "id": "mechanical-components",
    "name": "Mechanical Components",
    "rarity": "Uncommon"
  },
  {
    "id": "medium-ammo",
    "name": "Medium Ammo",
    "rarity": "Common"
  },
  {
    "id": "medium-gun-parts",
    "name": "Medium Gun Parts",
    "rarity": "Rare"
  },
  {
    "id": "medium-gun-parts-recipe",
    "name": "Medium Gun Parts Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "medium-shield",
    "name": "Medium Shield",
    "rarity": "Rare"
  },
  {
    "id": "metal-brackets",
    "name": "Metal Brackets",
    "rarity": "Uncommon"
  },
  {
    "id": "metal-parts",
    "name": "Metal Parts",
    "rarity": "Common"
  },
  {
    "id": "microscope",
    "name": "Microscope",
    "rarity": "Rare"
  },
  {
    "id": "mini-centrifuge",
    "name": "Mini Centrifuge",
    "rarity": "Rare"
  },
  {
    "id": "mod-components",
    "name": "Mod Components",
    "rarity": "Rare"
  },
  {
    "id": "moss",
    "name": "Moss",
    "rarity": "Rare"
  },
  {
    "id": "motor",
    "name": "Motor",
    "rarity": "Rare"
  },
  {
    "id": "mushroom",
    "name": "Mushroom",
    "rarity": "Uncommon"
  },
  {
    "id": "music-album",
    "name": "Music Album",
    "rarity": "Rare"
  },
  {
    "id": "music-box",
    "name": "Music Box",
    "rarity": "Rare"
  },
  {
    "id": "muzzle-brake-i",
    "name": "Muzzle Brake I",
    "rarity": "Common"
  },
  {
    "id": "muzzle-brake-ii",
    "name": "Muzzle Brake II",
    "rarity": "Uncommon"
  },
  {
    "id": "muzzle-brake-ii-recipe",
    "name": "Muzzle Brake II Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "muzzle-brake-iii",
    "name": "Muzzle Brake III",
    "rarity": "Rare"
  },
  {
    "id": "muzzle-brake-iii-recipe",
    "name": "Muzzle Brake III Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "noisemaker",
    "name": "Noisemaker",
    "rarity": "Common"
  },
  {
    "id": "anvil-splitter-recipe",
    "name": "not-in-game Anvil Splitter Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "horizontal-grip-blueprint",
    "name": "not-in-game Horizontal Grip Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "kinetic-converter-recipe",
    "name": "not-in-game Kinetic Converter Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "silencer-iii-recipe",
    "name": "not-in-game Silencer III Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "number-plate",
    "name": "Number Plate",
    "rarity": "Uncommon"
  },
  {
    "id": "oil",
    "name": "Oil",
    "rarity": "Uncommon"
  },
  {
    "id": "olives",
    "name": "Olives",
    "rarity": "Uncommon"
  },
  {
    "id": "orange-camo-origin-outfit",
    "name": "Orange Camo (Origin Outfit)",
    "rarity": "Common"
  },
  {
    "id": "osprey-recipe",
    "name": "Osprey Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "osprey-i",
    "name": "Osprey I",
    "rarity": "Rare"
  },
  {
    "id": "osprey-ii",
    "name": "Osprey II",
    "rarity": "Rare"
  },
  {
    "id": "osprey-iii",
    "name": "Osprey III",
    "rarity": "Rare"
  },
  {
    "id": "osprey-iv",
    "name": "Osprey IV",
    "rarity": "Rare"
  },
  {
    "id": "padded-stock",
    "name": "Padded Stock",
    "rarity": "Epic"
  },
  {
    "id": "padded-stock-recipe",
    "name": "Padded Stock Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "painted-box",
    "name": "Painted Box",
    "rarity": "Uncommon"
  },
  {
    "id": "patrol-car-key",
    "name": "Patrol Car Key",
    "rarity": "Uncommon"
  },
  {
    "id": "patrol-outfit",
    "name": "Patrol (Outfit)",
    "rarity": "Common"
  },
  {
    "id": "photoelectric-cloak",
    "name": "Photoelectric Cloak",
    "rarity": "Epic"
  },
  {
    "id": "plastic-parts",
    "name": "Plastic Parts",
    "rarity": "Common"
  },
  {
    "id": "playing-cards",
    "name": "Playing Cards",
    "rarity": "Rare"
  },
  {
    "id": "polluted-air-filter",
    "name": "Polluted Air Filter",
    "rarity": "Rare"
  },
  {
    "id": "pop-trigger",
    "name": "Pop Trigger",
    "rarity": "Uncommon"
  },
  {
    "id": "portable-television",
    "name": "Portable TV",
    "rarity": "Rare"
  },
  {
    "id": "poster-natural-wonder",
    "name": "Poster of Natural Wonder",
    "rarity": "Uncommon"
  },
  {
    "id": "pottery",
    "name": "Pottery",
    "rarity": "Uncommon"
  },
  {
    "id": "power-bank",
    "name": "Power Bank",
    "rarity": "Rare"
  },
  {
    "id": "power-cable",
    "name": "Power Cable",
    "rarity": "Rare"
  },
  {
    "id": "power-rod",
    "name": "Power Rod",
    "rarity": "Epic"
  },
  {
    "id": "prickly-pear",
    "name": "Prickly Pear",
    "rarity": "Common"
  },
  {
    "id": "processor",
    "name": "Processor",
    "rarity": "Rare"
  },
  {
    "id": "projector",
    "name": "Projector",
    "rarity": "Rare"
  },
  {
    "id": "pulse-mine",
    "name": "Pulse Mine",
    "rarity": "Uncommon"
  },
  {
    "id": "pulse-mine-blueprint",
    "name": "Pulse Mine Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "queen-reactor",
    "name": "Queen Reactor",
    "rarity": "Legendary"
  },
  {
    "id": "radio",
    "name": "Radio",
    "rarity": "Rare"
  },
  {
    "id": "radio-relay",
    "name": "Radio Relay",
    "rarity": "Rare"
  },
  {
    "id": "radio-renegade-outfit",
    "name": "Radio Renegade (Outfit)",
    "rarity": "Common"
  },
  {
    "id": "raider-hatch-key",
    "name": "Raider Hatch Key",
    "rarity": "Rare"
  },
  {
    "id": "rattler-i",
    "name": "Rattler I",
    "rarity": "Common"
  },
  {
    "id": "rattler-ii",
    "name": "Rattler II",
    "rarity": "Common"
  },
  {
    "id": "rattler-iii",
    "name": "Rattler III",
    "rarity": "Common"
  },
  {
    "id": "rattler-iv",
    "name": "Rattler IV",
    "rarity": "Common"
  },
  {
    "id": "recorder",
    "name": "Recorder",
    "rarity": "Uncommon"
  },
  {
    "id": "red-coral-jewelry",
    "name": "Red Coral Jewelry",
    "rarity": "Rare"
  },
  {
    "id": "red-light-stick",
    "name": "Red Light Stick",
    "rarity": "Common"
  },
  {
    "id": "red-light-stick-blueprint",
    "name": "Red Light Stick Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "refinement-1",
    "name": "Refinement 1",
    "rarity": "Common"
  },
  {
    "id": "remote-control",
    "name": "Remote Control",
    "rarity": "Rare"
  },
  {
    "id": "remote-raider-flare",
    "name": "Remote Raider Flare",
    "rarity": "Common"
  },
  {
    "id": "remote-raider-flare-blueprint",
    "name": "Remote Raider Flare Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "renegade-i",
    "name": "Renegade I",
    "rarity": "Rare"
  },
  {
    "id": "renegade-ii",
    "name": "Renegade II",
    "rarity": "Rare"
  },
  {
    "id": "renegade-iii",
    "name": "Renegade III",
    "rarity": "Rare"
  },
  {
    "id": "renegade-iv",
    "name": "Renegade IV",
    "rarity": "Rare"
  },
  {
    "id": "resin",
    "name": "Resin",
    "rarity": "Common"
  },
  {
    "id": "ripped-safety-vest",
    "name": "Ripped Safety Vest",
    "rarity": "Uncommon"
  },
  {
    "id": "rocketeer-part",
    "name": "Rocketeer Driver",
    "rarity": "Epic"
  },
  {
    "id": "rocket-thruster",
    "name": "Rocket Thruster",
    "rarity": "Rare"
  },
  {
    "id": "roots",
    "name": "Roots",
    "rarity": "Uncommon"
  },
  {
    "id": "rope",
    "name": "Rope",
    "rarity": "Rare"
  },
  {
    "id": "rosary",
    "name": "Rosary",
    "rarity": "Rare"
  },
  {
    "id": "rotary-encoder",
    "name": "Rotary Encoder",
    "rarity": "Rare"
  },
  {
    "id": "rubber-duck",
    "name": "Rubber Duck",
    "rarity": "Common"
  },
  {
    "id": "rubber-pad",
    "name": "Rubber Pad",
    "rarity": "Rare"
  },
  {
    "id": "rubber-parts-recipe",
    "name": "Rubber Parts",
    "rarity": "Common"
  },
  {
    "id": "ruined-accordion",
    "name": "Ruined Accordion",
    "rarity": "Rare"
  },
  {
    "id": "ruined-augment",
    "name": "Ruined Augment",
    "rarity": "Common"
  },
  {
    "id": "ruined-baton",
    "name": "Ruined Baton",
    "rarity": "Uncommon"
  },
  {
    "id": "ruined-handcuffs",
    "name": "Ruined Handcuffs",
    "rarity": "Uncommon"
  },
  {
    "id": "ruined-parachute",
    "name": "Ruined Parachute",
    "rarity": "Uncommon"
  },
  {
    "id": "ruined-riot-shield",
    "name": "Ruined Riot Shield",
    "rarity": "Rare"
  },
  {
    "id": "ruined-tactical-vest",
    "name": "Ruined Tactical Vest",
    "rarity": "Uncommon"
  },
  {
    "id": "rusted-bolts",
    "name": "Rusted Bolts",
    "rarity": "Uncommon"
  },
  {
    "id": "rusted-gear",
    "name": "Rusted Gear",
    "rarity": "Rare"
  },
  {
    "id": "rusted-shut-medical-kit",
    "name": "Rusted Shut Medical Kit",
    "rarity": "Rare"
  },
  {
    "id": "rusted-tools",
    "name": "Rusted Tools",
    "rarity": "Rare"
  },
  {
    "id": "rusty-arc-steel",
    "name": "Rusty ARC Steel",
    "rarity": "Uncommon"
  },
  {
    "id": "sample-cleaner",
    "name": "Sample Cleaner",
    "rarity": "Rare"
  },
  {
    "id": "seeker-grenade",
    "name": "Seeker Grenade",
    "rarity": "Uncommon"
  },
  {
    "id": "seeker-grenade-blueprint",
    "name": "Seeker Grenade Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "sensors-recipe",
    "name": "Sensors",
    "rarity": "Rare"
  },
  {
    "id": "sentinel-part",
    "name": "Sentinel Firing Core",
    "rarity": "Rare"
  },
  {
    "id": "shaker",
    "name": "Shaker",
    "rarity": "Uncommon"
  },
  {
    "id": "shield-recharger",
    "name": "Shield Recharger",
    "rarity": "Uncommon"
  },
  {
    "id": "shotgun-ammo",
    "name": "Shotgun ammo",
    "rarity": "Common"
  },
  {
    "id": "shotgun-choke-i",
    "name": "Shotgun Choke I",
    "rarity": "Common"
  },
  {
    "id": "shotgun-choke-ii",
    "name": "Shotgun Choke II",
    "rarity": "Uncommon"
  },
  {
    "id": "shotgun-choke-ii-recipe",
    "name": "Shotgun Choke II Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "shotgun-choke-iii",
    "name": "Shotgun Choke III",
    "rarity": "Rare"
  },
  {
    "id": "shotgun-choke-iii-recipe",
    "name": "Shotgun Choke III Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "shotgun-gun-parts",
    "name": "Shotgun Parts",
    "rarity": "Rare"
  },
  {
    "id": "shotgun-silencer",
    "name": "Shotgun Silencer",
    "rarity": "Epic"
  },
  {
    "id": "shotgun-silencer-blueprint",
    "name": "Shotgun Silencer Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "showstopper",
    "name": "Showstopper",
    "rarity": "Rare"
  },
  {
    "id": "showstopper-blueprint",
    "name": "Showstopper Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "shrapnel-grenade",
    "name": "Shrapnel Grenade",
    "rarity": "Uncommon"
  },
  {
    "id": "shredder-gyro",
    "name": "Shredder Gyro",
    "rarity": "Rare"
  },
  {
    "id": "signal-amplifier",
    "name": "Signal Amplifier",
    "rarity": "Rare"
  },
  {
    "id": "silencer-i",
    "name": "Silencer I",
    "rarity": "Uncommon"
  },
  {
    "id": "silencer-i-recipe",
    "name": "Silencer I Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "silencer-ii",
    "name": "Silencer II",
    "rarity": "Rare"
  },
  {
    "id": "silencer-ii-recipe",
    "name": "Silencer II Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "silencer-iii",
    "name": "Silencer III",
    "rarity": "Epic"
  },
  {
    "id": "silver-teaspoon-set",
    "name": "Silver Teaspoon Set",
    "rarity": "Rare"
  },
  {
    "id": "simple-gun-parts",
    "name": "Simple Gun Parts",
    "rarity": "Uncommon"
  },
  {
    "id": "smoke-grenade",
    "name": "Smoke Grenade",
    "rarity": "Rare"
  },
  {
    "id": "smoke-grenade-blueprint",
    "name": "Smoke Grenade Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "laser-trap-smoke-recipe",
    "name": "Smoke Grenade Trap",
    "rarity": "Rare"
  },
  {
    "id": "snap-blast-grenade",
    "name": "Snap Blast Grenade",
    "rarity": "Uncommon"
  },
  {
    "id": "snap-hook",
    "name": "Snap Hook",
    "rarity": "Legendary"
  },
  {
    "id": "snap-hook-recipe",
    "name": "Snap Hook Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "snitch-scanner",
    "name": "Snitch Scanner",
    "rarity": "Uncommon"
  },
  {
    "id": "snowball",
    "name": "Snowball",
    "rarity": "Common"
  },
  {
    "id": "spaceport-container-storage-key",
    "name": "Spaceport Container Storage Key",
    "rarity": "Rare"
  },
  {
    "id": "spaceport-ground-control-key",
    "name": "Spaceport Control Tower Key",
    "rarity": "Rare"
  },
  {
    "id": "spaceport-outskirts-bunker-key",
    "name": "Spaceport Outskirts Bunker Key",
    "rarity": "Rare"
  },
  {
    "id": "spaceport-trench-tower-key",
    "name": "Spaceport Trench Tower Key",
    "rarity": "Uncommon"
  },
  {
    "id": "spaceport-warehouse-key",
    "name": "Spaceport Warehouse Key",
    "rarity": "Uncommon"
  },
  {
    "id": "speaker-component",
    "name": "Speaker Component",
    "rarity": "Rare"
  },
  {
    "id": "spectrometer",
    "name": "Spectrometer",
    "rarity": "Rare"
  },
  {
    "id": "spectrum-analyzer",
    "name": "Spectrum Analyzer",
    "rarity": "Epic"
  },
  {
    "id": "spotter-relay",
    "name": "Spotter Relay",
    "rarity": "Uncommon"
  },
  {
    "id": "spring-cushion",
    "name": "Spring Cushion",
    "rarity": "Rare"
  },
  {
    "id": "stable-stock-i",
    "name": "Stable Stock I",
    "rarity": "Common"
  },
  {
    "id": "stable-stock-ii",
    "name": "Stable Stock II",
    "rarity": "Uncommon"
  },
  {
    "id": "stable-stock-ii-recipe",
    "name": "Stable Stock II Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "stable-stock-iii",
    "name": "Stable Stock III",
    "rarity": "Rare"
  },
  {
    "id": "stable-stock-iii-recipe",
    "name": "Stable Stock III Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "statuette",
    "name": "Statuette",
    "rarity": "Rare"
  },
  {
    "id": "spring",
    "name": "Steel Spring",
    "rarity": "Uncommon"
  },
  {
    "id": "stella-montis-archives-key",
    "name": "Stella Montis Archives Key",
    "rarity": "Epic"
  },
  {
    "id": "stella-montis-assembly-admin-key",
    "name": "Stella Montis Assembly Admin Key",
    "rarity": "Uncommon"
  },
  {
    "id": "stella-montis-medical-storage-key",
    "name": "Stella Montis Medical Storage Key",
    "rarity": "Uncommon"
  },
  {
    "id": "stella-montis-security-checkpoint-key",
    "name": "Stella Montis Security Checkpoint Key",
    "rarity": "Rare"
  },
  {
    "id": "sterilized-bandage",
    "name": "Sterilized Bandage",
    "rarity": "Rare"
  },
  {
    "id": "stitcher-i",
    "name": "Stitcher I",
    "rarity": "Common"
  },
  {
    "id": "stitcher-ii",
    "name": "Stitcher II",
    "rarity": "Common"
  },
  {
    "id": "stitcher-iii",
    "name": "Stitcher III",
    "rarity": "Common"
  },
  {
    "id": "stitcher-iv",
    "name": "Stitcher IV",
    "rarity": "Common"
  },
  {
    "id": "succulent-backpack-charm",
    "name": "Succulent (Backpack Charm)",
    "rarity": "Common"
  },
  {
    "id": "surge-shield-recharger",
    "name": "Surge Shield Recharger",
    "rarity": "Rare"
  },
  {
    "id": "surveyor-vault",
    "name": "Surveyor Vault",
    "rarity": "Rare"
  },
  {
    "id": "synthesized-fuel",
    "name": "Synthesized Fuel",
    "rarity": "Rare"
  },
  {
    "id": "syringe",
    "name": "Syringe",
    "rarity": "Rare"
  },
  {
    "id": "tactical-mk-1",
    "name": "Tactical Mk. 1",
    "rarity": "Uncommon"
  },
  {
    "id": "tactical-mk-2",
    "name": "Tactical Mk. 2",
    "rarity": "Rare"
  },
  {
    "id": "tactical-mk3-defensive",
    "name": "Tactical Mk.3 (Defensive)",
    "rarity": "Epic"
  },
  {
    "id": "tactical-mk3-defensive-blueprint",
    "name": "Tactical MK.3 (Defensive) Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "tactical-mk-3-healing",
    "name": "Tactical Mk. 3 (Healing)",
    "rarity": "Epic"
  },
  {
    "id": "tacical-mk3-healing-blueprint",
    "name": "Tactical MK.3 (Healing) Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "tagging-grenade",
    "name": "Tagging Grenade",
    "rarity": "Rare"
  },
  {
    "id": "tagging-grenade-recipe",
    "name": "Tagging Grenade Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "tangerine-warden-color",
    "name": "Tangerine (Warden Color)",
    "rarity": "Common"
  },
  {
    "id": "tattered-arc-lining",
    "name": "Tattered ARC Lining",
    "rarity": "Uncommon"
  },
  {
    "id": "tattered-clothes",
    "name": "Tattered Clothes",
    "rarity": "Uncommon"
  },
  {
    "id": "telemetry-transceiver",
    "name": "Telemetry Transceiver",
    "rarity": "Rare"
  },
  {
    "id": "tempest-i",
    "name": "Tempest I",
    "rarity": "Epic"
  },
  {
    "id": "tempest-i-recipe",
    "name": "Tempest I Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "tempest-ii",
    "name": "Tempest II",
    "rarity": "Epic"
  },
  {
    "id": "tempest-iii",
    "name": "Tempest III",
    "rarity": "Epic"
  },
  {
    "id": "tempest-iv",
    "name": "Tempest IV",
    "rarity": "Epic"
  },
  {
    "id": "thermostat",
    "name": "Thermostat",
    "rarity": "Rare"
  },
  {
    "id": "tick-pod",
    "name": "Tick Pod",
    "rarity": "Uncommon"
  },
  {
    "id": "toaster",
    "name": "Toaster",
    "rarity": "Rare"
  },
  {
    "id": "torch-ginger",
    "name": "Torch Ginger",
    "rarity": "Uncommon"
  },
  {
    "id": "torn-blanket",
    "name": "Torn Blanket",
    "rarity": "Rare"
  },
  {
    "id": "torn-book",
    "name": "Torn Book",
    "rarity": "Common"
  },
  {
    "id": "torrent-i-recipe",
    "name": "Torrente Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "torrente-i",
    "name": "Torrente I",
    "rarity": "Rare"
  },
  {
    "id": "torrente-ii",
    "name": "Torrente II",
    "rarity": "Rare"
  },
  {
    "id": "torrente-iii",
    "name": "Torrente III",
    "rarity": "Rare"
  },
  {
    "id": "torrente-iv",
    "name": "Torrente IV",
    "rarity": "Rare"
  },
  {
    "id": "trailblazer-grenade",
    "name": "Trailblazer Grenade",
    "rarity": "Rare"
  },
  {
    "id": "trailblazer-grenade-blueprint",
    "name": "Trailblazer Grenade Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "trigger-nade",
    "name": "Trigger Nade",
    "rarity": "Rare"
  },
  {
    "id": "trigger-nade-recipe",
    "name": "Trigger Nade Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "turbo-pump",
    "name": "Turbo Pump",
    "rarity": "Rare"
  },
  {
    "id": "unusable-weapon",
    "name": "Unusable Weapon",
    "rarity": "Rare"
  },
  {
    "id": "vase",
    "name": "Vase",
    "rarity": "Rare"
  },
  {
    "id": "venator-recipe",
    "name": "Venator Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "venator-i",
    "name": "Venator I",
    "rarity": "Rare"
  },
  {
    "id": "venator-ii",
    "name": "Venator II",
    "rarity": "Rare"
  },
  {
    "id": "venator-iii",
    "name": "Venator III",
    "rarity": "Rare"
  },
  {
    "id": "venator-iv",
    "name": "Venator IV",
    "rarity": "Rare"
  },
  {
    "id": "vertical-grip-i",
    "name": "Vertical Grip I",
    "rarity": "Common"
  },
  {
    "id": "vertical-grip-ii",
    "name": "Vertical Grip II",
    "rarity": "Uncommon"
  },
  {
    "id": "vertical-grip-ii-recipe",
    "name": "Vertical Grip II Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "vertical-grip-iii",
    "name": "Vertical Grip III",
    "rarity": "Rare"
  },
  {
    "id": "vertical-grip-iii-recipe",
    "name": "Vertical Grip III Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "very-comfortable-pillow",
    "name": "Very Comfortable Pillow",
    "rarity": "Uncommon"
  },
  {
    "id": "vita-shot",
    "name": "Vita Shot",
    "rarity": "Rare"
  },
  {
    "id": "vita-shot-recipe",
    "name": "Vita Shot Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "vita-spray",
    "name": "Vita Spray",
    "rarity": "Epic"
  },
  {
    "id": "vita-spray-recipe",
    "name": "Vita Spray Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "volcanic-rock",
    "name": "Volcanic Rock",
    "rarity": "Common"
  },
  {
    "id": "voltage-converter",
    "name": "Voltage Converter",
    "rarity": "Rare"
  },
  {
    "id": "vulcano-blueprint",
    "name": "Vulcano Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "vulcano-i",
    "name": "Vulcano I",
    "rarity": "Epic"
  },
  {
    "id": "vulcano-ii",
    "name": "Vulcano II",
    "rarity": "Epic"
  },
  {
    "id": "vulcano-iii",
    "name": "Vulcano III",
    "rarity": "Epic"
  },
  {
    "id": "vulcano-iv",
    "name": "Vulcano IV",
    "rarity": "Epic"
  },
  {
    "id": "warden-outfit",
    "name": "Warden (Outfit)",
    "rarity": "Common"
  },
  {
    "id": "wasp-driver",
    "name": "Wasp Driver",
    "rarity": "Rare"
  },
  {
    "id": "water-filter",
    "name": "Water Filter",
    "rarity": "Rare"
  },
  {
    "id": "water-pump",
    "name": "Water Pump",
    "rarity": "Rare"
  },
  {
    "id": "wires-recipe",
    "name": "Wires",
    "rarity": "Uncommon"
  },
  {
    "id": "wolfpack",
    "name": "WolfPack",
    "rarity": "Epic"
  },
  {
    "id": "wolfpack-recipe",
    "name": "Wolfpack Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "yellow-light-stick",
    "name": "Yellow Light Stick",
    "rarity": "Common"
  },
  {
    "id": "yellow-light-stick-blueprint",
    "name": "Yellow Light Stick Blueprint",
    "rarity": "Legendary"
  },
  {
    "id": "zipline",
    "name": "Zipline",
    "rarity": "Rare"
  }
];

// Create a lookup map for quick access
export const itemsById = new Map<string, RequiredItem>(
  allItems.map((item) => [item.id, item])
);

// Get item by ID
export const getItemById = (id: string): RequiredItem | undefined =>
  itemsById.get(id);
