import type { Keeplist } from "../types";

// System keeplists - default state provided by the app
// Generated by Keeplist Builder on 2026-01-07T13:24:09.728Z
export const systemKeeplists: Keeplist[] = [
  {
    id: "workbenches",
    name: "Workbenches",
    isSystem: true,
    items: [
      { itemId: "rusted-tools", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "wasp-driver", qtyOwned: 0, qtyRequired: 8, isCompleted: false },
      { itemId: "rusted-gear", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "sentinel-part", qtyOwned: 0, qtyRequired: 4, isCompleted: false },
      { itemId: "power-cable", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "hornet-driver", qtyOwned: 0, qtyRequired: 5, isCompleted: false },
    ],
  },
  {
    id: "expedition-1",
    name: "Expedition 1",
    isSystem: true,
    items: [
      { itemId: "cooling-fan", qtyOwned: 0, qtyRequired: 5, isCompleted: false },
    ],
  },
];
