import type { Keeplist } from "../types";

// System keeplists - default state provided by the app
// Generated by Keeplist Builder on 2026-01-07T13:34:01.743Z
export const systemKeeplists: Keeplist[] = [
  {
    id: "workbenches",
    name: "Workbenches",
    isSystem: true,
    items: [
      { itemId: "rusted-tools", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "wasp-driver", qtyOwned: 0, qtyRequired: 8, isCompleted: false },
      { itemId: "rusted-gear", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "sentinel-part", qtyOwned: 0, qtyRequired: 4, isCompleted: false },
      { itemId: "power-cable", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "hornet-driver", qtyOwned: 0, qtyRequired: 5, isCompleted: false },
      { itemId: "industrial-battery", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "bastion-part", qtyOwned: 0, qtyRequired: 6, isCompleted: false },
      { itemId: "cracked-bioscanner", qtyOwned: 0, qtyRequired: 2, isCompleted: false },
      { itemId: "tick-pod", qtyOwned: 0, qtyRequired: 8, isCompleted: false },
      { itemId: "rusted-shut-medical-kit", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "antiseptic", qtyOwned: 0, qtyRequired: 8, isCompleted: false },
      { itemId: "surveyor-vault", qtyOwned: 0, qtyRequired: 5, isCompleted: false },
      { itemId: "synthesized-fuel", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "pop-trigger", qtyOwned: 0, qtyRequired: 5, isCompleted: false },
      { itemId: "laboratory-reagents", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "explosive-compound", qtyOwned: 0, qtyRequired: 5, isCompleted: false },
      { itemId: "rocketeer-part", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "damaged-heat-sink", qtyOwned: 0, qtyRequired: 2, isCompleted: false },
      { itemId: "snitch-scanner", qtyOwned: 0, qtyRequired: 6, isCompleted: false },
      { itemId: "fried-motherboard", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "leaper-pulse-unit", qtyOwned: 0, qtyRequired: 4, isCompleted: false },
      { itemId: "toaster", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "arc-motion-core", qtyOwned: 0, qtyRequired: 5, isCompleted: false },
      { itemId: "fireball-burner", qtyOwned: 0, qtyRequired: 8, isCompleted: false },
      { itemId: "motor", qtyOwned: 0, qtyRequired: 3, isCompleted: false },
      { itemId: "arc-circuitry", qtyOwned: 0, qtyRequired: 10, isCompleted: false },
      { itemId: "bombardier-cell", qtyOwned: 0, qtyRequired: 6, isCompleted: false },
    ],
  },
  {
    id: "expedition-1",
    name: "Expedition 1",
    isSystem: true,
    items: [
      { itemId: "cooling-fan", qtyOwned: 0, qtyRequired: 5, isCompleted: false },
    ],
  },
];
